//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Interfaces.serviciosTaxa {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SOAPSoap", Namespace="http://tempuri.org/")]
    public partial class SOAP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SeleccionarTaxasOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarTaxaPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionarTaxaEspeciePorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarFotoPrincipalPorIdTaxaExamenOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarTaxasEspeciesAnfibiosExamenOperationCompleted;
        
        private System.Threading.SendOrPostCallback seleccionarTaxaMultimediaPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarTaxaOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarTaxaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarTaxaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOAP() {
            this.Url = global::Interfaces.Properties.Settings.Default.Interfaces_serviciosTaxa_SOAP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SeleccionarTaxasCompletedEventHandler SeleccionarTaxasCompleted;
        
        /// <remarks/>
        public event SeleccionarTaxaPorIdCompletedEventHandler SeleccionarTaxaPorIdCompleted;
        
        /// <remarks/>
        public event SeleccionarTaxaEspeciePorIdCompletedEventHandler SeleccionarTaxaEspeciePorIdCompleted;
        
        /// <remarks/>
        public event seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompletedEventHandler seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompleted;
        
        /// <remarks/>
        public event seleccionarFotoPrincipalPorIdTaxaExamenCompletedEventHandler seleccionarFotoPrincipalPorIdTaxaExamenCompleted;
        
        /// <remarks/>
        public event seleccionarTaxasEspeciesAnfibiosExamenCompletedEventHandler seleccionarTaxasEspeciesAnfibiosExamenCompleted;
        
        /// <remarks/>
        public event seleccionarTaxaMultimediaPorIdCompletedEventHandler seleccionarTaxaMultimediaPorIdCompleted;
        
        /// <remarks/>
        public event insertarTaxaCompletedEventHandler insertarTaxaCompleted;
        
        /// <remarks/>
        public event actualizarTaxaCompletedEventHandler actualizarTaxaCompleted;
        
        /// <remarks/>
        public event eliminarTaxaCompletedEventHandler eliminarTaxaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarTaxas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxa[] SeleccionarTaxas() {
            object[] results = this.Invoke("SeleccionarTaxas", new object[0]);
            return ((taxa[])(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarTaxasAsync() {
            this.SeleccionarTaxasAsync(null);
        }
        
        /// <remarks/>
        public void SeleccionarTaxasAsync(object userState) {
            if ((this.SeleccionarTaxasOperationCompleted == null)) {
                this.SeleccionarTaxasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarTaxasOperationCompleted);
            }
            this.InvokeAsync("SeleccionarTaxas", new object[0], this.SeleccionarTaxasOperationCompleted, userState);
        }
        
        private void OnSeleccionarTaxasOperationCompleted(object arg) {
            if ((this.SeleccionarTaxasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarTaxasCompleted(this, new SeleccionarTaxasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarTaxaPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxa SeleccionarTaxaPorId(int idTaxa) {
            object[] results = this.Invoke("SeleccionarTaxaPorId", new object[] {
                        idTaxa});
            return ((taxa)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarTaxaPorIdAsync(int idTaxa) {
            this.SeleccionarTaxaPorIdAsync(idTaxa, null);
        }
        
        /// <remarks/>
        public void SeleccionarTaxaPorIdAsync(int idTaxa, object userState) {
            if ((this.SeleccionarTaxaPorIdOperationCompleted == null)) {
                this.SeleccionarTaxaPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarTaxaPorIdOperationCompleted);
            }
            this.InvokeAsync("SeleccionarTaxaPorId", new object[] {
                        idTaxa}, this.SeleccionarTaxaPorIdOperationCompleted, userState);
        }
        
        private void OnSeleccionarTaxaPorIdOperationCompleted(object arg) {
            if ((this.SeleccionarTaxaPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarTaxaPorIdCompleted(this, new SeleccionarTaxaPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionarTaxaEspeciePorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxaespecie SeleccionarTaxaEspeciePorId(int idTaxa) {
            object[] results = this.Invoke("SeleccionarTaxaEspeciePorId", new object[] {
                        idTaxa});
            return ((taxaespecie)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionarTaxaEspeciePorIdAsync(int idTaxa) {
            this.SeleccionarTaxaEspeciePorIdAsync(idTaxa, null);
        }
        
        /// <remarks/>
        public void SeleccionarTaxaEspeciePorIdAsync(int idTaxa, object userState) {
            if ((this.SeleccionarTaxaEspeciePorIdOperationCompleted == null)) {
                this.SeleccionarTaxaEspeciePorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionarTaxaEspeciePorIdOperationCompleted);
            }
            this.InvokeAsync("SeleccionarTaxaEspeciePorId", new object[] {
                        idTaxa}, this.SeleccionarTaxaEspeciePorIdOperationCompleted, userState);
        }
        
        private void OnSeleccionarTaxaEspeciePorIdOperationCompleted(object arg) {
            if ((this.SeleccionarTaxaEspeciePorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionarTaxaEspeciePorIdCompleted(this, new SeleccionarTaxaEspeciePorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExame" +
            "n", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxapublica[] seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamen(int parametro) {
            object[] results = this.Invoke("seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamen", new object[] {
                        parametro});
            return ((taxapublica[])(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenAsync(int parametro) {
            this.seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenAsync(parametro, null);
        }
        
        /// <remarks/>
        public void seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenAsync(int parametro, object userState) {
            if ((this.seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenOperationCompleted == null)) {
                this.seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenOperationCompleted);
            }
            this.InvokeAsync("seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamen", new object[] {
                        parametro}, this.seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenOperationCompleted, userState);
        }
        
        private void OnseleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenOperationCompleted(object arg) {
            if ((this.seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompleted(this, new seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarFotoPrincipalPorIdTaxaExamen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxacatalogo seleccionarFotoPrincipalPorIdTaxaExamen(int parametro) {
            object[] results = this.Invoke("seleccionarFotoPrincipalPorIdTaxaExamen", new object[] {
                        parametro});
            return ((taxacatalogo)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarFotoPrincipalPorIdTaxaExamenAsync(int parametro) {
            this.seleccionarFotoPrincipalPorIdTaxaExamenAsync(parametro, null);
        }
        
        /// <remarks/>
        public void seleccionarFotoPrincipalPorIdTaxaExamenAsync(int parametro, object userState) {
            if ((this.seleccionarFotoPrincipalPorIdTaxaExamenOperationCompleted == null)) {
                this.seleccionarFotoPrincipalPorIdTaxaExamenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarFotoPrincipalPorIdTaxaExamenOperationCompleted);
            }
            this.InvokeAsync("seleccionarFotoPrincipalPorIdTaxaExamen", new object[] {
                        parametro}, this.seleccionarFotoPrincipalPorIdTaxaExamenOperationCompleted, userState);
        }
        
        private void OnseleccionarFotoPrincipalPorIdTaxaExamenOperationCompleted(object arg) {
            if ((this.seleccionarFotoPrincipalPorIdTaxaExamenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarFotoPrincipalPorIdTaxaExamenCompleted(this, new seleccionarFotoPrincipalPorIdTaxaExamenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarTaxasEspeciesAnfibiosExamen", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxaamphibia[] seleccionarTaxasEspeciesAnfibiosExamen(int parametro, string opcion) {
            object[] results = this.Invoke("seleccionarTaxasEspeciesAnfibiosExamen", new object[] {
                        parametro,
                        opcion});
            return ((taxaamphibia[])(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarTaxasEspeciesAnfibiosExamenAsync(int parametro, string opcion) {
            this.seleccionarTaxasEspeciesAnfibiosExamenAsync(parametro, opcion, null);
        }
        
        /// <remarks/>
        public void seleccionarTaxasEspeciesAnfibiosExamenAsync(int parametro, string opcion, object userState) {
            if ((this.seleccionarTaxasEspeciesAnfibiosExamenOperationCompleted == null)) {
                this.seleccionarTaxasEspeciesAnfibiosExamenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarTaxasEspeciesAnfibiosExamenOperationCompleted);
            }
            this.InvokeAsync("seleccionarTaxasEspeciesAnfibiosExamen", new object[] {
                        parametro,
                        opcion}, this.seleccionarTaxasEspeciesAnfibiosExamenOperationCompleted, userState);
        }
        
        private void OnseleccionarTaxasEspeciesAnfibiosExamenOperationCompleted(object arg) {
            if ((this.seleccionarTaxasEspeciesAnfibiosExamenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarTaxasEspeciesAnfibiosExamenCompleted(this, new seleccionarTaxasEspeciesAnfibiosExamenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/seleccionarTaxaMultimediaPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public taxamultimedia seleccionarTaxaMultimediaPorId(int idtaxa) {
            object[] results = this.Invoke("seleccionarTaxaMultimediaPorId", new object[] {
                        idtaxa});
            return ((taxamultimedia)(results[0]));
        }
        
        /// <remarks/>
        public void seleccionarTaxaMultimediaPorIdAsync(int idtaxa) {
            this.seleccionarTaxaMultimediaPorIdAsync(idtaxa, null);
        }
        
        /// <remarks/>
        public void seleccionarTaxaMultimediaPorIdAsync(int idtaxa, object userState) {
            if ((this.seleccionarTaxaMultimediaPorIdOperationCompleted == null)) {
                this.seleccionarTaxaMultimediaPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnseleccionarTaxaMultimediaPorIdOperationCompleted);
            }
            this.InvokeAsync("seleccionarTaxaMultimediaPorId", new object[] {
                        idtaxa}, this.seleccionarTaxaMultimediaPorIdOperationCompleted, userState);
        }
        
        private void OnseleccionarTaxaMultimediaPorIdOperationCompleted(object arg) {
            if ((this.seleccionarTaxaMultimediaPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.seleccionarTaxaMultimediaPorIdCompleted(this, new seleccionarTaxaMultimediaPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarTaxa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long insertarTaxa(taxa nuevaTaxa) {
            object[] results = this.Invoke("insertarTaxa", new object[] {
                        nuevaTaxa});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void insertarTaxaAsync(taxa nuevaTaxa) {
            this.insertarTaxaAsync(nuevaTaxa, null);
        }
        
        /// <remarks/>
        public void insertarTaxaAsync(taxa nuevaTaxa, object userState) {
            if ((this.insertarTaxaOperationCompleted == null)) {
                this.insertarTaxaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarTaxaOperationCompleted);
            }
            this.InvokeAsync("insertarTaxa", new object[] {
                        nuevaTaxa}, this.insertarTaxaOperationCompleted, userState);
        }
        
        private void OninsertarTaxaOperationCompleted(object arg) {
            if ((this.insertarTaxaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarTaxaCompleted(this, new insertarTaxaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarTaxa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool actualizarTaxa(taxa taxaModificada) {
            object[] results = this.Invoke("actualizarTaxa", new object[] {
                        taxaModificada});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarTaxaAsync(taxa taxaModificada) {
            this.actualizarTaxaAsync(taxaModificada, null);
        }
        
        /// <remarks/>
        public void actualizarTaxaAsync(taxa taxaModificada, object userState) {
            if ((this.actualizarTaxaOperationCompleted == null)) {
                this.actualizarTaxaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarTaxaOperationCompleted);
            }
            this.InvokeAsync("actualizarTaxa", new object[] {
                        taxaModificada}, this.actualizarTaxaOperationCompleted, userState);
        }
        
        private void OnactualizarTaxaOperationCompleted(object arg) {
            if ((this.actualizarTaxaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarTaxaCompleted(this, new actualizarTaxaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarTaxa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarTaxa(taxa taxaEliminado) {
            object[] results = this.Invoke("eliminarTaxa", new object[] {
                        taxaEliminado});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarTaxaAsync(taxa taxaEliminado) {
            this.eliminarTaxaAsync(taxaEliminado, null);
        }
        
        /// <remarks/>
        public void eliminarTaxaAsync(taxa taxaEliminado, object userState) {
            if ((this.eliminarTaxaOperationCompleted == null)) {
                this.eliminarTaxaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarTaxaOperationCompleted);
            }
            this.InvokeAsync("eliminarTaxa", new object[] {
                        taxaEliminado}, this.eliminarTaxaOperationCompleted, userState);
        }
        
        private void OneliminarTaxaOperationCompleted(object arg) {
            if ((this.eliminarTaxaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarTaxaCompleted(this, new eliminarTaxaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxa {
        
        private especie[] especiesField;
        
        private multimedia[] multimediasField;
        
        private nombrecomun[] nombrecomunsField;
        
        private taxapublicacion[] taxapublicacionsField;
        
        private long idTaxaField;
        
        private string nombreField;
        
        private string nombreCortoField;
        
        private bool enEcuadorField;
        
        private bool endemicaField;
        
        private System.Nullable<long> idTaxaPadreField;
        
        private long idCatalogoField;
        
        private bool publicarEnWebField;
        
        private System.Nullable<System.DateTime> fechaModificacionField;
        
        private string usuarioModificacionField;
        
        private System.Nullable<long> idPublicacionReporteField;
        
        private System.Nullable<int> anoField;
        
        /// <comentarios/>
        public especie[] especies {
            get {
                return this.especiesField;
            }
            set {
                this.especiesField = value;
            }
        }
        
        /// <comentarios/>
        public multimedia[] multimedias {
            get {
                return this.multimediasField;
            }
            set {
                this.multimediasField = value;
            }
        }
        
        /// <comentarios/>
        public nombrecomun[] nombrecomuns {
            get {
                return this.nombrecomunsField;
            }
            set {
                this.nombrecomunsField = value;
            }
        }
        
        /// <comentarios/>
        public taxapublicacion[] taxapublicacions {
            get {
                return this.taxapublicacionsField;
            }
            set {
                this.taxapublicacionsField = value;
            }
        }
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreCorto {
            get {
                return this.nombreCortoField;
            }
            set {
                this.nombreCortoField = value;
            }
        }
        
        /// <comentarios/>
        public bool EnEcuador {
            get {
                return this.enEcuadorField;
            }
            set {
                this.enEcuadorField = value;
            }
        }
        
        /// <comentarios/>
        public bool Endemica {
            get {
                return this.endemicaField;
            }
            set {
                this.endemicaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdTaxaPadre {
            get {
                return this.idTaxaPadreField;
            }
            set {
                this.idTaxaPadreField = value;
            }
        }
        
        /// <comentarios/>
        public long IdCatalogo {
            get {
                return this.idCatalogoField;
            }
            set {
                this.idCatalogoField = value;
            }
        }
        
        /// <comentarios/>
        public bool PublicarEnWeb {
            get {
                return this.publicarEnWebField;
            }
            set {
                this.publicarEnWebField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <comentarios/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdPublicacionReporte {
            get {
                return this.idPublicacionReporteField;
            }
            set {
                this.idPublicacionReporteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class especie {
        
        private long idEspecieField;
        
        private long idTaxaField;
        
        private string etimologiaField;
        
        private string taxonomiaField;
        
        private string habitatBiologiaField;
        
        private string dietaField;
        
        private string reproduccionField;
        
        private string informacionAdicionalField;
        
        private string comentarioEstatusPoblacionalField;
        
        private string distribucionField;
        
        private string distribucionGlobalField;
        
        private string observacionZonaAltitudinalField;
        
        private string rangoAltitudinalField;
        
        private string referenciaAreaProtegidaField;
        
        private string compiladorField;
        
        private System.Nullable<System.DateTime> fechaCompilacionField;
        
        private string autoriaCompiladorField;
        
        private string editorField;
        
        private System.Nullable<System.DateTime> fechaEdicionField;
        
        private string autoriaEditorField;
        
        private System.Nullable<System.DateTime> fechaActualizacionField;
        
        private string agradecimientoField;
        
        private System.Nullable<System.DateTime> fechaModificacionField;
        
        private string usuarioModificacionField;
        
        private string categoriaField;
        
        /// <comentarios/>
        public long IdEspecie {
            get {
                return this.idEspecieField;
            }
            set {
                this.idEspecieField = value;
            }
        }
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public string Etimologia {
            get {
                return this.etimologiaField;
            }
            set {
                this.etimologiaField = value;
            }
        }
        
        /// <comentarios/>
        public string Taxonomia {
            get {
                return this.taxonomiaField;
            }
            set {
                this.taxonomiaField = value;
            }
        }
        
        /// <comentarios/>
        public string HabitatBiologia {
            get {
                return this.habitatBiologiaField;
            }
            set {
                this.habitatBiologiaField = value;
            }
        }
        
        /// <comentarios/>
        public string Dieta {
            get {
                return this.dietaField;
            }
            set {
                this.dietaField = value;
            }
        }
        
        /// <comentarios/>
        public string Reproduccion {
            get {
                return this.reproduccionField;
            }
            set {
                this.reproduccionField = value;
            }
        }
        
        /// <comentarios/>
        public string InformacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
            }
        }
        
        /// <comentarios/>
        public string ComentarioEstatusPoblacional {
            get {
                return this.comentarioEstatusPoblacionalField;
            }
            set {
                this.comentarioEstatusPoblacionalField = value;
            }
        }
        
        /// <comentarios/>
        public string Distribucion {
            get {
                return this.distribucionField;
            }
            set {
                this.distribucionField = value;
            }
        }
        
        /// <comentarios/>
        public string DistribucionGlobal {
            get {
                return this.distribucionGlobalField;
            }
            set {
                this.distribucionGlobalField = value;
            }
        }
        
        /// <comentarios/>
        public string ObservacionZonaAltitudinal {
            get {
                return this.observacionZonaAltitudinalField;
            }
            set {
                this.observacionZonaAltitudinalField = value;
            }
        }
        
        /// <comentarios/>
        public string RangoAltitudinal {
            get {
                return this.rangoAltitudinalField;
            }
            set {
                this.rangoAltitudinalField = value;
            }
        }
        
        /// <comentarios/>
        public string ReferenciaAreaProtegida {
            get {
                return this.referenciaAreaProtegidaField;
            }
            set {
                this.referenciaAreaProtegidaField = value;
            }
        }
        
        /// <comentarios/>
        public string Compilador {
            get {
                return this.compiladorField;
            }
            set {
                this.compiladorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaCompilacion {
            get {
                return this.fechaCompilacionField;
            }
            set {
                this.fechaCompilacionField = value;
            }
        }
        
        /// <comentarios/>
        public string AutoriaCompilador {
            get {
                return this.autoriaCompiladorField;
            }
            set {
                this.autoriaCompiladorField = value;
            }
        }
        
        /// <comentarios/>
        public string Editor {
            get {
                return this.editorField;
            }
            set {
                this.editorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaEdicion {
            get {
                return this.fechaEdicionField;
            }
            set {
                this.fechaEdicionField = value;
            }
        }
        
        /// <comentarios/>
        public string AutoriaEditor {
            get {
                return this.autoriaEditorField;
            }
            set {
                this.autoriaEditorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
            }
        }
        
        /// <comentarios/>
        public string Agradecimiento {
            get {
                return this.agradecimientoField;
            }
            set {
                this.agradecimientoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <comentarios/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
        
        /// <comentarios/>
        public string Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxamultimedia {
        
        private long idMultimediaField;
        
        private string tituloField;
        
        private string nombreArchivoField;
        
        private long idTaxaField;
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fechaModificacionField;
        
        private string usuarioModificacionField;
        
        /// <comentarios/>
        public long IdMultimedia {
            get {
                return this.idMultimediaField;
            }
            set {
                this.idMultimediaField = value;
            }
        }
        
        /// <comentarios/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <comentarios/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxaamphibia {
        
        private long idTaxaField;
        
        private long idAmphibiaField;
        
        private string sinonimiaField;
        
        private string nombreField;
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public long IdAmphibia {
            get {
                return this.idAmphibiaField;
            }
            set {
                this.idAmphibiaField = value;
            }
        }
        
        /// <comentarios/>
        public string Sinonimia {
            get {
                return this.sinonimiaField;
            }
            set {
                this.sinonimiaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxacatalogo {
        
        private long idTaxaField;
        
        private string nombreField;
        
        private string nombreArchivoField;
        
        private string descripcionField;
        
        private string descrpcionCField;
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        public string DescrpcionC {
            get {
                return this.descrpcionCField;
            }
            set {
                this.descrpcionCField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxapublica {
        
        private long idTaxaField;
        
        private string nombreField;
        
        private long idPublicacionField;
        
        private string tituloField;
        
        private string tituloSecundarioField;
        
        private bool editorField;
        
        private string editorialField;
        
        private string volumenField;
        
        private string numeroField;
        
        private string citaField;
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public long IdPublicacion {
            get {
                return this.idPublicacionField;
            }
            set {
                this.idPublicacionField = value;
            }
        }
        
        /// <comentarios/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <comentarios/>
        public string TituloSecundario {
            get {
                return this.tituloSecundarioField;
            }
            set {
                this.tituloSecundarioField = value;
            }
        }
        
        /// <comentarios/>
        public bool Editor {
            get {
                return this.editorField;
            }
            set {
                this.editorField = value;
            }
        }
        
        /// <comentarios/>
        public string Editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
            }
        }
        
        /// <comentarios/>
        public string Volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
            }
        }
        
        /// <comentarios/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <comentarios/>
        public string Cita {
            get {
                return this.citaField;
            }
            set {
                this.citaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxaespecie {
        
        private long idTaxaField;
        
        private string nombreField;
        
        private string habitatBiologiaField;
        
        private string comentarioEstatusPoblacionalField;
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string HabitatBiologia {
            get {
                return this.habitatBiologiaField;
            }
            set {
                this.habitatBiologiaField = value;
            }
        }
        
        /// <comentarios/>
        public string ComentarioEstatusPoblacional {
            get {
                return this.comentarioEstatusPoblacionalField;
            }
            set {
                this.comentarioEstatusPoblacionalField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class taxapublicacion {
        
        private long idTaxaPublicacionField;
        
        private long idTaxaField;
        
        private long idPublicacionField;
        
        private bool principalField;
        
        private System.Nullable<bool> borradoField;
        
        private System.Nullable<System.DateTime> fechaModificacionField;
        
        private string usuarioModificacionField;
        
        /// <comentarios/>
        public long IdTaxaPublicacion {
            get {
                return this.idTaxaPublicacionField;
            }
            set {
                this.idTaxaPublicacionField = value;
            }
        }
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public long IdPublicacion {
            get {
                return this.idPublicacionField;
            }
            set {
                this.idPublicacionField = value;
            }
        }
        
        /// <comentarios/>
        public bool Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Borrado {
            get {
                return this.borradoField;
            }
            set {
                this.borradoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <comentarios/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class nombrecomun {
        
        private long idNombreComunField;
        
        private long idTaxaField;
        
        private string nombreField;
        
        private string comentarioField;
        
        private bool principalField;
        
        private System.Nullable<int> ordenField;
        
        private System.Nullable<long> idPublicacionField;
        
        private System.Nullable<bool> borradoField;
        
        private System.Nullable<System.DateTime> fechaModificacionField;
        
        private string usuarioModificacionField;
        
        /// <comentarios/>
        public long IdNombreComun {
            get {
                return this.idNombreComunField;
            }
            set {
                this.idNombreComunField = value;
            }
        }
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
            }
        }
        
        /// <comentarios/>
        public bool Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdPublicacion {
            get {
                return this.idPublicacionField;
            }
            set {
                this.idPublicacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Borrado {
            get {
                return this.borradoField;
            }
            set {
                this.borradoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <comentarios/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class multimedia {
        
        private long idMultimediaField;
        
        private string tituloField;
        
        private string nombreArchivoField;
        
        private long idTaxaField;
        
        private System.Nullable<long> idTipoField;
        
        private string descripcionField;
        
        private System.Nullable<bool> principalField;
        
        private bool descargaField;
        
        private long idCatalogoField;
        
        private bool enlaceExternoField;
        
        private System.Nullable<bool> borradoField;
        
        private System.Nullable<System.DateTime> fechaModificacionField;
        
        private string usuarioModificacionField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        private string fuenteBibliograficaField;
        
        private string duracion_msField;
        
        private string frecuenciaInicial_KHzField;
        
        private string frecuenciaMaxima_KHzField;
        
        private string frecuenciaFinal_KHzField;
        
        private string frecuenciaMinima_KHzField;
        
        private string frecuenciaPuntoInflexion_KHzField;
        
        private string frecuenciaMaximaEnergia_KHzField;
        
        private string anchoBanda_KHzField;
        
        private string softwareField;
        
        private string grabadoraField;
        
        private string detectorField;
        
        private string situacionGrabacionField;
        
        private string responsableField;
        
        private string duracionMinimaField;
        
        private string duracionMaximaField;
        
        private string frecuenciaInicialMinimaField;
        
        private string frecuenciaInicialMaximaField;
        
        private string frecuenciaMaximaMinimaField;
        
        private string frecuenciaMaximaMaximaField;
        
        private string frecuenciaFinalMinimaField;
        
        private string frecuenciaFinalMaximaField;
        
        private string frecuenciaMinimaMinimaField;
        
        private string frecuenciaMinimaMaximaField;
        
        private string frecuenciaPuntoInflexionMinimaField;
        
        private string frecuenciaPuntoInflexionMaximaField;
        
        private string frecuenciaCaracteristicaField;
        
        private string frecuenciaCaracteristicaMinimaField;
        
        private string frecuenciaCaracteristicaMaximaField;
        
        private string frecuenciaMaximaEnergiaMinimaField;
        
        private string frecuenciaMaximaEnergiaMaximaField;
        
        private string anchoBandaMinimaField;
        
        private string anchoBandaMaximaField;
        
        /// <comentarios/>
        public long IdMultimedia {
            get {
                return this.idMultimediaField;
            }
            set {
                this.idMultimediaField = value;
            }
        }
        
        /// <comentarios/>
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
            }
        }
        
        /// <comentarios/>
        public long IdTaxa {
            get {
                return this.idTaxaField;
            }
            set {
                this.idTaxaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdTipo {
            get {
                return this.idTipoField;
            }
            set {
                this.idTipoField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <comentarios/>
        public bool Descarga {
            get {
                return this.descargaField;
            }
            set {
                this.descargaField = value;
            }
        }
        
        /// <comentarios/>
        public long IdCatalogo {
            get {
                return this.idCatalogoField;
            }
            set {
                this.idCatalogoField = value;
            }
        }
        
        /// <comentarios/>
        public bool EnlaceExterno {
            get {
                return this.enlaceExternoField;
            }
            set {
                this.enlaceExternoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Borrado {
            get {
                return this.borradoField;
            }
            set {
                this.borradoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
            }
        }
        
        /// <comentarios/>
        public string UsuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <comentarios/>
        public string FuenteBibliografica {
            get {
                return this.fuenteBibliograficaField;
            }
            set {
                this.fuenteBibliograficaField = value;
            }
        }
        
        /// <comentarios/>
        public string Duracion_ms {
            get {
                return this.duracion_msField;
            }
            set {
                this.duracion_msField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaInicial_KHz {
            get {
                return this.frecuenciaInicial_KHzField;
            }
            set {
                this.frecuenciaInicial_KHzField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMaxima_KHz {
            get {
                return this.frecuenciaMaxima_KHzField;
            }
            set {
                this.frecuenciaMaxima_KHzField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaFinal_KHz {
            get {
                return this.frecuenciaFinal_KHzField;
            }
            set {
                this.frecuenciaFinal_KHzField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMinima_KHz {
            get {
                return this.frecuenciaMinima_KHzField;
            }
            set {
                this.frecuenciaMinima_KHzField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaPuntoInflexion_KHz {
            get {
                return this.frecuenciaPuntoInflexion_KHzField;
            }
            set {
                this.frecuenciaPuntoInflexion_KHzField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMaximaEnergia_KHz {
            get {
                return this.frecuenciaMaximaEnergia_KHzField;
            }
            set {
                this.frecuenciaMaximaEnergia_KHzField = value;
            }
        }
        
        /// <comentarios/>
        public string AnchoBanda_KHz {
            get {
                return this.anchoBanda_KHzField;
            }
            set {
                this.anchoBanda_KHzField = value;
            }
        }
        
        /// <comentarios/>
        public string Software {
            get {
                return this.softwareField;
            }
            set {
                this.softwareField = value;
            }
        }
        
        /// <comentarios/>
        public string Grabadora {
            get {
                return this.grabadoraField;
            }
            set {
                this.grabadoraField = value;
            }
        }
        
        /// <comentarios/>
        public string Detector {
            get {
                return this.detectorField;
            }
            set {
                this.detectorField = value;
            }
        }
        
        /// <comentarios/>
        public string SituacionGrabacion {
            get {
                return this.situacionGrabacionField;
            }
            set {
                this.situacionGrabacionField = value;
            }
        }
        
        /// <comentarios/>
        public string Responsable {
            get {
                return this.responsableField;
            }
            set {
                this.responsableField = value;
            }
        }
        
        /// <comentarios/>
        public string DuracionMinima {
            get {
                return this.duracionMinimaField;
            }
            set {
                this.duracionMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string DuracionMaxima {
            get {
                return this.duracionMaximaField;
            }
            set {
                this.duracionMaximaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaInicialMinima {
            get {
                return this.frecuenciaInicialMinimaField;
            }
            set {
                this.frecuenciaInicialMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaInicialMaxima {
            get {
                return this.frecuenciaInicialMaximaField;
            }
            set {
                this.frecuenciaInicialMaximaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMaximaMinima {
            get {
                return this.frecuenciaMaximaMinimaField;
            }
            set {
                this.frecuenciaMaximaMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMaximaMaxima {
            get {
                return this.frecuenciaMaximaMaximaField;
            }
            set {
                this.frecuenciaMaximaMaximaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaFinalMinima {
            get {
                return this.frecuenciaFinalMinimaField;
            }
            set {
                this.frecuenciaFinalMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaFinalMaxima {
            get {
                return this.frecuenciaFinalMaximaField;
            }
            set {
                this.frecuenciaFinalMaximaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMinimaMinima {
            get {
                return this.frecuenciaMinimaMinimaField;
            }
            set {
                this.frecuenciaMinimaMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMinimaMaxima {
            get {
                return this.frecuenciaMinimaMaximaField;
            }
            set {
                this.frecuenciaMinimaMaximaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaPuntoInflexionMinima {
            get {
                return this.frecuenciaPuntoInflexionMinimaField;
            }
            set {
                this.frecuenciaPuntoInflexionMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaPuntoInflexionMaxima {
            get {
                return this.frecuenciaPuntoInflexionMaximaField;
            }
            set {
                this.frecuenciaPuntoInflexionMaximaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaCaracteristica {
            get {
                return this.frecuenciaCaracteristicaField;
            }
            set {
                this.frecuenciaCaracteristicaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaCaracteristicaMinima {
            get {
                return this.frecuenciaCaracteristicaMinimaField;
            }
            set {
                this.frecuenciaCaracteristicaMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaCaracteristicaMaxima {
            get {
                return this.frecuenciaCaracteristicaMaximaField;
            }
            set {
                this.frecuenciaCaracteristicaMaximaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMaximaEnergiaMinima {
            get {
                return this.frecuenciaMaximaEnergiaMinimaField;
            }
            set {
                this.frecuenciaMaximaEnergiaMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string FrecuenciaMaximaEnergiaMaxima {
            get {
                return this.frecuenciaMaximaEnergiaMaximaField;
            }
            set {
                this.frecuenciaMaximaEnergiaMaximaField = value;
            }
        }
        
        /// <comentarios/>
        public string AnchoBandaMinima {
            get {
                return this.anchoBandaMinimaField;
            }
            set {
                this.anchoBandaMinimaField = value;
            }
        }
        
        /// <comentarios/>
        public string AnchoBandaMaxima {
            get {
                return this.anchoBandaMaximaField;
            }
            set {
                this.anchoBandaMaximaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SeleccionarTaxasCompletedEventHandler(object sender, SeleccionarTaxasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarTaxasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarTaxasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SeleccionarTaxaPorIdCompletedEventHandler(object sender, SeleccionarTaxaPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarTaxaPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarTaxaPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SeleccionarTaxaEspeciePorIdCompletedEventHandler(object sender, SeleccionarTaxaEspeciePorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionarTaxaEspeciePorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionarTaxaEspeciePorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxaespecie Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxaespecie)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompletedEventHandler(object sender, seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarPublicacionesSeleccionarPublicacionesPorIdTaxaExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxapublica[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxapublica[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void seleccionarFotoPrincipalPorIdTaxaExamenCompletedEventHandler(object sender, seleccionarFotoPrincipalPorIdTaxaExamenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarFotoPrincipalPorIdTaxaExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarFotoPrincipalPorIdTaxaExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxacatalogo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxacatalogo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void seleccionarTaxasEspeciesAnfibiosExamenCompletedEventHandler(object sender, seleccionarTaxasEspeciesAnfibiosExamenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarTaxasEspeciesAnfibiosExamenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarTaxasEspeciesAnfibiosExamenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxaamphibia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxaamphibia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void seleccionarTaxaMultimediaPorIdCompletedEventHandler(object sender, seleccionarTaxaMultimediaPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seleccionarTaxaMultimediaPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal seleccionarTaxaMultimediaPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public taxamultimedia Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((taxamultimedia)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void insertarTaxaCompletedEventHandler(object sender, insertarTaxaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarTaxaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarTaxaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void actualizarTaxaCompletedEventHandler(object sender, actualizarTaxaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarTaxaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarTaxaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void eliminarTaxaCompletedEventHandler(object sender, eliminarTaxaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarTaxaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarTaxaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591