//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class autor
    {
        public autor()
        {
            this.autorbiografias = new List<autorbiografia>();
            this.publicacionautors = new List<publicacionautor>();
        }
    
        public long IdAutor { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string EnlaceBiografia { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual List<autorbiografia> autorbiografias { get; set; }
        public virtual List<publicacionautor> publicacionautors { get; set; }
    }
}
