//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    public partial class catalogo
    {
        public catalogo()
        {
            this.especiecatalogoes = new List<especiecatalogo>();
            this.ImagenEspecimen = new List<ImagenEspeciman>();
            this.multimedias = new List<multimedia>();
            this.nombrecomuncatalogoes = new List<nombrecomuncatalogo>();
            this.publicacioncatalogoes = new List<publicacioncatalogo>();
            this.publicacionenlaces = new List<publicacionenlace>();
            this.reptiliacatalogoes = new List<reptiliacatalogo>();
        }
    
        public long IdCatalogo { get; set; }
        public string Nombre { get; set; }
        public string Sigla { get; set; }
        public string Descripcion { get; set; }
        public long IdTipoCatalogo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }

        [XmlIgnore]
        public virtual tipocatalogo tipocatalogo { get; set; }
        [XmlIgnore]
        public virtual List<especiecatalogo> especiecatalogoes { get; set; }
        [XmlIgnore]
        public virtual List<ImagenEspeciman> ImagenEspecimen { get; set; }
        [XmlIgnore]
        public virtual List<multimedia> multimedias { get; set; }
        [XmlIgnore]
        public virtual List<nombrecomuncatalogo> nombrecomuncatalogoes { get; set; }
        [XmlIgnore]
        public virtual List<publicacioncatalogo> publicacioncatalogoes { get; set; }
        [XmlIgnore]
        public virtual List<publicacionenlace> publicacionenlaces { get; set; }
        [XmlIgnore]
        public virtual List<reptiliacatalogo> reptiliacatalogoes { get; set; }
    }
}
