//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColaReporte
    {
        public long Id { get; set; }
        public string SessionId { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> HoraPeticion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdCatalogo1 { get; set; }
        public Nullable<int> IdCatalogo2 { get; set; }
        public Nullable<int> IdCatalogo3 { get; set; }
        public Nullable<int> IdCatalogo4 { get; set; }
        public Nullable<int> IdCatalogo5 { get; set; }
        public Nullable<int> IdCatalogo6 { get; set; }
        public Nullable<int> IdCatalogo7 { get; set; }
        public Nullable<int> IdCatalogo8 { get; set; }
        public Nullable<long> IdTaxaOrden { get; set; }
        public Nullable<long> IdTaxa { get; set; }
        public string NombreTaxaGenero { get; set; }
        public string NombreTaxaEspecie { get; set; }
        public string NombreComunP { get; set; }
        public string NombreAutor { get; set; }
        public Nullable<int> AnioPublicacion { get; set; }
        public string AutoriaEditor { get; set; }
        public Nullable<bool> Endemica { get; set; }
        public Nullable<int> numeroRegistros { get; set; }
        public string rutaSalida { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string NombreVisitante { get; set; }
        public string InstitucionVisitante { get; set; }
        public string Categoria { get; set; }
        public string RutaDescarga { get; set; }
        public string TipoReporte { get; set; }
    }
}
