//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenEspeciman
    {
        public long IdImagenEspecimen { get; set; }
        public string Titulo { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<long> IdEspecimen { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IdCatalogo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual especiman especiman { get; set; }
    }
}
