//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidad
    {
        public long IdLocalidad { get; set; }
        public long IdDivisionGeopolitica { get; set; }
        public string Nombre { get; set; }
        public string NombreVerbatim { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string UtmN { get; set; }
        public string UtmE { get; set; }
        public string Altura { get; set; }
        public Nullable<decimal> Extension { get; set; }
        public Nullable<decimal> ErrorMaximaDistancia { get; set; }
        public Nullable<System.DateTime> FechaUltimoCambio { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    }
}
