//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.PERMISOSPERFILs = new HashSet<PERMISOSPERFIL>();
        }
    
        public long IDMENU { get; set; }
        public string NOMBREMENU { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public string USUARIOMODIFICACION { get; set; }
    
        public virtual ICollection<PERMISOSPERFIL> PERMISOSPERFILs { get; set; }
    }
}
