//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class nombrecomunpublicacion
    {
        public long idnombrecomunpublicacion { get; set; }
        public long idnombrecomun { get; set; }
        public long idpublicacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual nombrecomun nombrecomun { get; set; }
        public virtual publicacion publicacion { get; set; }
    }
}
