//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class publicacioncatalogo
    {
        public long IdPublicacionCatalogo { get; set; }
        public long IdPublicacion { get; set; }
        public long IdCatalogo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string Criterio { get; set; }
        public string PublicacionListaRoja { get; set; }
    
        public virtual catalogo catalogo { get; set; }
        public virtual publicacion publicacion { get; set; }
    }
}
