//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    public partial class publicacion
    {
        public publicacion()
        {
            this.especimen = new List<especiman>();
            this.nombrecomuns = new List<nombrecomun>();
            this.nombrecomunpublicacions = new List<nombrecomunpublicacion>();
            this.publicacionautors = new List<publicacionautor>();
            this.publicacioncatalogoes = new List<publicacioncatalogo>();
            this.publicacionenlaces = new List<publicacionenlace>();
            this.sinonimoes = new List<sinonimo>();
            this.taxapublicacions = new List<taxapublicacion>();
        }
    
        public long IdPublicacion { get; set; }
        public string Titulo { get; set; }
        public string TituloSecundario { get; set; }
        public bool Editor { get; set; }
        public string Editorial { get; set; }
        public string Volumen { get; set; }
        public string Numero { get; set; }
        public string Pagina { get; set; }
        public string PalabrasClave { get; set; }
        public string Resumen { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCreacionRegistro { get; set; }
        public bool PublicacionDelQcaz { get; set; }
        public bool PublicaEnNoticias { get; set; }
        public bool PublicaEnWeb { get; set; }
        public bool PublicaEnCV { get; set; }
        public Nullable<int> IdExterno { get; set; }
        public string FuenteIdExterno { get; set; }
        public string Publisher { get; set; }
        public string PubLocalidad { get; set; }
        public string Cita { get; set; }
        public string CitaCorta { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        [XmlIgnore]
        public virtual List<especiman> especimen { get; set; }
        [XmlIgnore]
        public virtual List<nombrecomun> nombrecomuns { get; set; }
        [XmlIgnore]
        public virtual List<nombrecomunpublicacion> nombrecomunpublicacions { get; set; }
        [XmlIgnore]
        public virtual List<publicacionautor> publicacionautors { get; set; }
        [XmlIgnore]
        public virtual List<publicacioncatalogo> publicacioncatalogoes { get; set; }
        [XmlIgnore]
        public virtual List<publicacionenlace> publicacionenlaces { get; set; }
        [XmlIgnore]
        public virtual List<sinonimo> sinonimoes { get; set; }
        [XmlIgnore]
        public virtual List<taxapublicacion> taxapublicacions { get; set; }
    }
}
