//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    public partial class publicacionenlace
    {
        public long IdPublicacionEnlace { get; set; }
        public string NombreArchivo { get; set; }
        public string EnlaceArchivo { get; set; }
        public string TextoEnlace { get; set; }
        public long IdPublicacion { get; set; }
        public long IdCatalogo { get; set; }
        public bool Descarga { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        [XmlIgnore]
        public virtual catalogo catalogo { get; set; }
        public virtual publicacion publicacion { get; set; }
    }
}
