//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class reptilia
    {
        public reptilia()
        {
            this.reptiliacatalogoes = new HashSet<reptiliacatalogo>();
        }
    
        public long IdReptilia { get; set; }
        public long IdEspecie { get; set; }
        public string Sinonimia { get; set; }
        public string Identificacion { get; set; }
        public string ColorEnVida { get; set; }
        public string ColorEnPreservacion { get; set; }
        public string Morfometria { get; set; }
        public string LongitudTotalMacho { get; set; }
        public string SVLMacho { get; set; }
        public string ReferenciaSVLMacho { get; set; }
        public string LongitudTotalHembra { get; set; }
        public string SVLHembra { get; set; }
        public string ReferenciaSVLHembra { get; set; }
        public string LepidosisLagartija { get; set; }
        public string ComentarioTamano { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual especie especie { get; set; }
        public virtual ICollection<reptiliacatalogo> reptiliacatalogoes { get; set; }
    }
}
