//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxaaudio
    {
        public long IdTaxaAudio { get; set; }
        public long IdTaxa { get; set; }
        public long IdAudio { get; set; }
        public long IdCatalogo { get; set; }
        public byte PublicaEnWeb { get; set; }
        public Nullable<byte> OrdenPresentacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    }
}
