//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo
    {
        public tipo()
        {
            this.multimedias = new HashSet<multimedia>();
        }
    
        public long IdTipo { get; set; }
        public long IdTaxa { get; set; }
        public string NumeroMuseo { get; set; }
        public string Medidas { get; set; }
        public string Comentario { get; set; }
        public bool Principal { get; set; }
        public long IdCatalogo { get; set; }
        public Nullable<long> IdLocalidad { get; set; }
        public Nullable<bool> Borrado { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string LocalidadDescripcion { get; set; }
    
        public virtual ICollection<multimedia> multimedias { get; set; }
        public virtual taxa taxa { get; set; }
    }
}
