//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipocatalogo
    {
        public tipocatalogo()
        {
            this.catalogoes = new HashSet<catalogo>();
            this.tipocatalogo1 = new HashSet<tipocatalogo>();
        }
    
        public long IdTipoCatalogo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> IdTipoCatalogoPadre { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual ICollection<catalogo> catalogoes { get; set; }
        public virtual ICollection<tipocatalogo> tipocatalogo1 { get; set; }
        public virtual tipocatalogo tipocatalogo2 { get; set; }
    }
}
