//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class verificacionlocalidad
    {
        public long IdVerificacionLocalidad { get; set; }
        public long IdLocalidad { get; set; }
        public long IdPersonal { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observacion { get; set; }
        public string Fuente { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    }
}
